import functions
import components

functions.gameStart()
# TODO MAIN - IN COMPONENTS REVWRITE FORMATTING INTO FORMATTING BY FUNCTION formattingConsole !!
# TODO 1) CHECK POTENTIAL PLAYERS AGE BY DATE OF BIRTH IN A FUNCTIONS
# TODO 2) FINISH RULES
# TODO 3) FINISH INITIAL FUNCTIONS IN functions.py

